name: recolor_env
channels:
  - defaults
dependencies:
  - python=3.11
  - torch=2.5.1
  - torchvision=0.20.1
  - wandb=0.18.5
  - accelerate=1.1.0
  - opencv-python
  - matplotlib=3.9.2
  - scikit-image=0.24.0
  - colorthief=0.2.1
  - pip:
    - pylette==4.0.0
    - streamlit==1.0.0